[1-2단계] - Join Query를 만들어 Entity화 해보기
next-step/jpa-association pull request #33
Opened 2023-11-10 07:08 UTC by zinzoddari

안녕하세요 태화님!!!!!!!!!

일단 원하는 결과 및 작동은 나와서 뿌듯하지만, 코드가 이게 맞나 싶습니다 ㅎ.ㅎ..;
가장 고민인 부분은, @OneToMany 하나만 생각하고 작성한 코드기에, 이 외의 연관관계가 들어올 때에는 어떻게 만드는게 좋을지... 감이 안오는 부분 하나랑,

또 List 값을 담아주기 위해서 별도 ResultMapper 부분에 List type의 경우, 해당 List의 Entity를 찾아 하나씩 List에 add 해주는 형식으로 구현을 했는데, 이게 맞는지? 혹은 최선의 코드일지? 잘 모르겠습니다... 🥲

한 번 태화님의 의견을 도움 받고 싶어 PR 쓰윽 올려 봅니다
이번 PR도 잘 부탁 드리겠습니다 🙇🏻‍♀️

2023-11-11 00:16 UTC, wooobo requested changes
안녕하세요 진주님! 

코멘트 남겨 놓았는데, 추가적인 관점 떠오르면 코멘트 더 남겨볼께요!
어려운 미션인데ㅜㅜ 마지막까지 화이팅입니다!!

👍 👍 👍

2023-11-11 00:16 UTC, wooobo commented on src/test/java/persistence/sql/dml/SelectQueryTest.java
>          String q = query.select(methodName, tableName, columns, joinColumn, 1);
저같은 경우에는, 
`query.selectJoin` 이런식으로 진행했었어요~

query 객체에서  select메소드에서, join인지도 판단해야되고 다른 조건이 추가 되면 또 판단해야 한다면 
select 가 하나의 책임을 가지기 좀 어렵겠는데? 라는 생각을 했었어요.

그래서 저는 `join`판단을 상위 레이어로 올렸었어요!
그래야지 추후 확장성에서 좀 더 유현하지 않을까? 생각이 되었기 때문이었어요!

`join`에 대한 판단을 `쿼리 뎁스`까지 안주는 관점인거죠.
근데 진주님 하신것도 진심으로 맞다고 생각해요! 관점 공유정도로 봐주세요~

2023-11-11 00:16 UTC, wooobo commented on src/main/java/jdbc/ResultMapper.java
>  package jdbc;
> 가장 고민인 부분은, @OneToMany 하나만 생각하고 작성한 코드기에, 이 외의 연관관계가 들어올 때에는 어떻게 만드는게 좋을지... 감이 안오는 부분 하나랑,...

우선은 `OneToMany`에 집중해보는것은 어떨까요?

2023-11-11 00:16 UTC, wooobo commented on src/test/java/persistence/sql/dml/SelectQueryTest.java
>          String q = query.select(methodName, tableName, columns, joinColumn, 1);
어디에서 판단할꺼냐에 따라서 설계과 많이 변화하는 부분이기 때문에
어디에서 판단하는 로직을 넣는게 좋은지 고민해보시면 좋을 것 같아요!

2023-11-11 00:16 UTC, wooobo commented on src/test/java/persistence/sql/dml/SelectQueryTest.java
>          String q = query.select(methodName, tableName, columns, joinColumn, 1);
`String q = query.select(methodName, tableName, columns, joinColumn, 1);`

주입시키는 매개변수가 다소 많아요!
객체지향에서 전달하는 변수를 최소화하는게 좋고 메시지를 명확하게(메소드 이름)하는것이 중요해요~
왜냐면, 전달하는 매개변수가 많아 지면 그만큼 책임또한 많아질수 있기때문이에요.

하지만, 매개변수를 어쩔수 없이 전달해야하는 상황이라고 한다면 그 변수들을 가지는 객체로 만들어서 하나로 전달해볼수 있을것 같구요!
그렇게 한다면 
```
private boolean isJoin() {
        return joinColumn != null;
    }
```
에 대한 책임이  `SelectQuery` 에서 가지지 않고 해당 객체에게 물어볼수있겟죠!

2023-11-13 01:14 UTC, zinzoddari commented
안녕하세요 태화님!!!!
우선, 원래도 EntityMeta 라는 객체 안에 관련 객체들 모아서 한 번에 전달 주었다가, [ EntityPersister ]를 구현하면서, 예제 코드대로 풀어서 코드를 작성하게 되었습니다... 그래서 사실 왜 다시 합쳐야하는거지? 싶지만 또 파라미터를 많이 전달하는건 보기 안좋다고는 생각을 하여
다시 EntityMeta라는 객체가 생기게 되었습니다;

사실 이게 태화님이 의도하신 바인지는 잘 모르겠으나 일단 제가 생각한 방향대로 수정을 해 보았습니다..
하지만 쿼리를 만드는 객체 (ex. SelectQuery)의 경우 EntityMeta로 받았으나, 이걸 다시 풀어서 사용을 해 주어야 한다고 생각을 하기에,
태화님이 말씀해주신
`private boolean isJoin() {
    return joinColumn != null;
}`
이 부분은 객체 자체에 묻기가 가능한지?는 잘 모르겠어서 수정을 별도로 못하였습니다 🥲

뭔가 제가 다른 방향으로 수정을 하고 있다고 생각이 드신다면 알려주세요 🥹!!!!!!!

2023-11-13 12:11 UTC, wooobo approved these changes
안녕하세요 진주님!

피드백에 대해서 고민해주셔서 감사합니다 😂 😂 
자유롭게 생각해주세요~ 피드백에 대해 그대로 반영안해도 됩니다! ㅎㅎ
다만, 저는 다양한 시도를 해보시고 여러가지의 관점을 느껴보시는게 가장 많은것을 얻어갈수 있지 않을까 생각하고있습니다 ㅎㅎ

그럼 다음 단계도 화이팅입니다~

2023-11-13 12:11 UTC, wooobo commented on src/main/java/persistence/sql/dml/SelectQuery.java
> +        this.methodName = entityMeta.getMethodName();
> 하지만 쿼리를 만드는 객체 (ex. SelectQuery)의 경우 EntityMeta로 받았으나, 이걸 다시 풀어서 사용을 해 주어야 한다고 생각을 하기에,

그렇긴하네요... 지금 구조상 EntityMeta를 전달전달해야하니 의미가 다소 없어 보이긴하네요 ㅜㅜ 
그래도 도전해보시고 구조상으로 개선해야 될 포인트가 보였다면 그거면 충분하다고 생각합니다 ㅎㅎ
처음부터 구조를 결코 완벽하게 구현할수 없으니까요 ^^;;


> 사실 이게 태화님이 의도하신 바인지는 잘 모르겠으나 일단 제가 생각한 방향대로 수정을 해 보았습니다..

제거 의도한바는 저의 관점을 보고 다양하게 시도해보시는것이었습니다! ㅎㅎ

2023-11-13 12:11 UTC, wooobo commented on src/main/java/persistence/sql/dml/SelectQuery.java
> +        this.methodName = entityMeta.getMethodName();
> `private boolean isJoin() { return joinColumn != null; }`
이 부분은 객체 자체에 묻기가 가능한지?는 잘 모르겠어서 수정을 별도로 못하였습니다🥲

맞아요... 저도 지금 구조상으론 딱히 아이디어가 떠오르지는 않네요 ㅜㅜ! 
😂 😂 😂

2023-11-13 12:12 UTC, merged