1단계 - OneToMany (FetchType.EAGER)
next-step/jpa-association pull request #90
Opened 2024-03-25 13:26 UTC by JoyDaheeCha

안녕하세요-! 업무가 바빠 리뷰 요청이 늦었습니다 ㅠ 이번 리뷰도 잘 부탁드려요~ :)

2024-03-26 02:43 UTC, jwee0330 requested changes
안녕하세요 다희님 🙂
업무도 바쁜데 포기하지 않고 미션을 진행하시는 모습이 정말 대단하십니다 👍 
1단계 구현 하시느라 정말 고생많으셨습니다!
몇 가지 개선사항에 대한 피드백을 드렸습니다. 확인하시고 수정하신 뒤 다시 PR 요청 부탁드릴게요!
미션 진행 중 궁금하신 부분은 편하게 DM 또는 코멘트 부탁드립니다.
끝까지 파이팅하세요 💪

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/entity/exception/NoOneToManyAssociationException.java
> +}
Custom 예외 👍

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/entity/manager/EntityManagerImpl.java
>          return Optional.of(addedEntity);
jakarta.persistence.EntityManager 에 명시된 스팩을 준수해주세요 :)
<img width="538" alt="image" src="https://github.com/next-step/jpa-association/assets/54702844/0868afa9-5314-4a73-bfe0-fed8f41b0bec">

현재 디비에 id 가 1 인 row 만 존재한다고 가정할 때, 2로 조회하면 결과값이 없어서 null 이 반환되어야 할텐데요
지금 처럼 find 요청이 Optional 을 반환하는 구조에서 2로 조회 요청을 하면 무슨 문제가 발생할까요?

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/entity/manager/EntityManagerImpl.java
>          entityEntry.finishStatusUpdate();
SAVING 은 실제 insert 쿼리가 실행되기 직전의 상태값입니다 🥲

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/entity/persistencecontext/EntityEntries.java
> +    }
저는 EntityEntry 도 메시지로 전달하게 하는편이 조금더 유연한 구조에 어울리는것 같다고 생각하는데
혹시 어떻게 생각하시나요?

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/sql/common/DtoMapper.java
> +            String columnName = annotation == null || annotation.name().isEmpty()? camelToSnake(field.getName()) : annotation.name();
가독성이 조금 떨어지는것 같네요 🥲
적절한 메소드로 책임을 나눠보셔도 좋을것 같습니다

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/sql/common/DtoMapper.java
> +                .replaceAll(match -> String.format("%s_%s", match.group(1), match.group(2)));
Pattern 객체는 생성 비용이 비싼 객체 매번 만드시는건 좋지 않습니다 🥲

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/clause/column/ColumnClauses.java
> +                .filter(field -> !field.isAnnotationPresent(Transient.class) && !field.isAnnotationPresent(OneToMany.class))
```suggestion
                .filter(field -> !field.isAnnotationPresent(Transient.class))
                .filter(field -> !field.isAnnotationPresent(OneToMany.class))
```
이렇게 작성하는 편이 가독성이 더 좋은것 같은데 어떻게 생각하세요?

2024-03-26 02:43 UTC, jwee0330 commented on src/main/java/persistence/sql/ddl/clause/column/JoinClause.java
> +}
조인절에 대한 개념을 아주 잘 만들어 주셨습니다.
다만 현재 로직은 연관관계 객체가 2개 이상일 경우에는 join 쿼리가 올바르게 만들어 지지 않을것 같습니다 🥲
이부분에 대한 개선이 필요해 보이네요

2024-04-07 04:34 UTC, JoyDaheeCha commented on src/main/java/persistence/entity/manager/EntityManagerImpl.java
>          return Optional.of(addedEntity);
넵 Optional.empty가 반환될것 같아요. 다만 결과값이 없을 수도 있다는것을 명시하기 위해서 저는 Optional을 사용했는데요-! Optional을 사용하는것이 좋지 않은 경우는 비용 외에 어떤 이유가 있을까요?

2024-04-07 17:02 UTC, JoyDaheeCha commented on src/main/java/persistence/entity/manager/EntityManagerImpl.java
>          entityEntry.finishStatusUpdate();
entityPersister.insert 구문이 실행되어야, entity 의 id 값이 세팅이 되어서요 😢
혹시 save 전 id 를 받아올 수 있는 방법이 있을까요?

2024-04-07 17:05 UTC, JoyDaheeCha commented on src/main/java/persistence/entity/persistencecontext/EntityEntries.java
> +    }
EntityEntry는 new 키워드로 생성되고 있는데, 어떤 방식으로 메시지를 전달하면 좋을까요? 힌트 부탁드립니다~

2024-04-07 17:11 UTC, JoyDaheeCha commented
리뷰어님 안녕하세요-! 늦게나마 리뷰 신청 다시 드립니다! 이해가 가지 않는 부분이 있어서 질문 각각 남겨두었습니다. 감사합니다. :)

2024-04-08 08:24 UTC, jwee0330 commented on src/main/java/persistence/entity/manager/EntityManagerImpl.java
>          return Optional.of(addedEntity);
옵셔널을 사용하지 말라는 이유는 스펙에 맞지 않기 때문이에요~!
다른 개발을 하실때는 적절한 위치에 마음껏 사용하셔도 좋아요.
다만 저희는 JAVA 스펙을 준수하는 라이브러리를 만드는 과정이기 때문에
interface 에 맞지 않는다면 호환이 되지 않을것 같네요!
`jakarta.persistence.EntityManager 에 명시된 스팩` 을 준수해야 합니다 :)
수정 부탁드립니다 :)

2024-04-08 08:26 UTC, jwee0330 commented on src/main/java/persistence/entity/manager/EntityManagerImpl.java
>          entityEntry.finishStatusUpdate();
`org.hibernate.persister.entity.EntityPersister` 의 setIdentifier 메소드를 참조해서 작업해주세요🙏🏻

2024-04-08 10:31 UTC, jwee0330 requested changes
안녕하세요 다희님 🙂
포기하지 않고 끝까지 작업하시는 모습이 정말 멋있습니다 👍 
질문 주신 부분들에 코멘트 드렸습니다. 아직 피드백이 전부 반영되지 않아서 RC 드릴게요~!
수정 후 다시 PR 요청 부탁드립니다 🙇🏻‍♂️

2024-04-08 10:31 UTC, jwee0330 commented on src/main/java/persistence/entity/persistencecontext/EntityEntries.java
> +    }
오래전 피드백이라 잘 기억이 안나긴하는데요
아마 이부분 때문에 드린 피드백인것 같네요
이미 키를 생성하셨는데 키를 전달하지 않고 또 생성하시네요

<img width="665" alt="image" src="https://github.com/next-step/jpa-association/assets/54702844/78a83862-9ad6-4ccf-a9ac-83ee2b795b6b">

2024-05-01 07:27 UTC, JoyDaheeCha commented
리뷰어님 안녕하세요-! 다시 미션 도전해보려합니다-! 가능하실때 리뷰 부탁드립니다 감사합니다~

2024-05-03 10:14 UTC, jwee0330 approved these changes
안녕하세요 다희님🙂
바빠서 리뷰가 조금 늦었습니다🥲

먼저 드렸던 피드백을 전부 잘 반영해 주셔서 머지하도록 하겠습니다~!
2단계 구현 부탁드립니다!
다시 미션을 진행하시는 모습이 정말 멋지십니다 👍
끝까지 응원하겠습니다 💪

2024-05-03 10:14 UTC, jwee0330 commented on src/main/java/persistence/entity/manager/EntityManager.java
> +    void persist(Object entity);
이제 JPA 스팩 호환이 되겠어요 👍

2024-05-03 10:14 UTC, jwee0330 commented on src/main/java/persistence/entity/persistencecontext/PersistenceContextImpl.java
> +        Class<?> clazz = entity.getClass();Long id = new PrimaryKey(entity).getPrimaryKeyValue(entity);
```suggestion
        Class<?> clazz = entity.getClass();
        Long id = new PrimaryKey(entity).getPrimaryKeyValue(entity);
```
; 뒤에 개행이 누락된것 같아요

2024-05-03 10:14 UTC, merged